/*
 * REGISTRO DE ASSETS DE ESCENARIO (solo la app: Metro resuelve los `require`)
 * Cada id apunta a un GLB original sin modificar (licencias: docs/environment-assets.md).
 * Los datos puros (pack, escala, licencia) están en EnvironmentAssetInfo.ts.
 */
/* eslint-disable @typescript-eslint/no-require-imports */
export const ENV_ASSET_MODULES: Readonly<Record<string, number>> = {
  'home/cactus': require('@/assets/environments/home/cactus.glb'),
  'home/couch_medium': require('@/assets/environments/home/couch_medium.glb'),
  'home/curtains_double': require('@/assets/environments/home/curtains_double.glb'),
  'home/door': require('@/assets/environments/home/door.glb'),
  'home/drawer': require('@/assets/environments/home/drawer.glb'),
  'home/fireplace': require('@/assets/environments/home/fireplace.glb'),
  'home/houseplant_2': require('@/assets/environments/home/houseplant_2.glb'),
  'home/houseplant_3': require('@/assets/environments/home/houseplant_3.glb'),
  'home/houseplant_5': require('@/assets/environments/home/houseplant_5.glb'),
  'home/light_floor_2': require('@/assets/environments/home/light_floor_2.glb'),
  'home/night_stand': require('@/assets/environments/home/night_stand.glb'),
  'home/round_rug': require('@/assets/environments/home/round_rug.glb'),
  'home/rug': require('@/assets/environments/home/rug.glb'),
  'home/shelf_small': require('@/assets/environments/home/shelf_small.glb'),
  'home/table_lamp': require('@/assets/environments/home/table_lamp.glb'),
  'home/table_round_small': require('@/assets/environments/home/table_round_small.glb'),
  'home/window_large': require('@/assets/environments/home/window_large.glb'),
  'outdoor/fence_gate': require('@/assets/environments/outdoor/fence_gate.glb'),
  'outdoor/fence_simple': require('@/assets/environments/outdoor/fence_simple.glb'),
  'outdoor/flower_purpleA': require('@/assets/environments/outdoor/flower_purpleA.glb'),
  'outdoor/flower_redA': require('@/assets/environments/outdoor/flower_redA.glb'),
  'outdoor/flower_yellowA': require('@/assets/environments/outdoor/flower_yellowA.glb'),
  'outdoor/grass': require('@/assets/environments/outdoor/grass.glb'),
  'outdoor/grass_large': require('@/assets/environments/outdoor/grass_large.glb'),
  'outdoor/lily_large': require('@/assets/environments/outdoor/lily_large.glb'),
  'outdoor/lily_small': require('@/assets/environments/outdoor/lily_small.glb'),
  'outdoor/log': require('@/assets/environments/outdoor/log.glb'),
  'outdoor/log_large': require('@/assets/environments/outdoor/log_large.glb'),
  'outdoor/mushroom_redGroup': require('@/assets/environments/outdoor/mushroom_redGroup.glb'),
  'outdoor/path_stone': require('@/assets/environments/outdoor/path_stone.glb'),
  'outdoor/path_stoneCircle': require('@/assets/environments/outdoor/path_stoneCircle.glb'),
  'outdoor/plant_bush': require('@/assets/environments/outdoor/plant_bush.glb'),
  'outdoor/plant_bushDetailed': require('@/assets/environments/outdoor/plant_bushDetailed.glb'),
  'outdoor/plant_bushLarge': require('@/assets/environments/outdoor/plant_bushLarge.glb'),
  'outdoor/pot_large': require('@/assets/environments/outdoor/pot_large.glb'),
  'outdoor/rock_largeA': require('@/assets/environments/outdoor/rock_largeA.glb'),
  'outdoor/rock_smallA': require('@/assets/environments/outdoor/rock_smallA.glb'),
  'outdoor/stump_round': require('@/assets/environments/outdoor/stump_round.glb'),
  'outdoor/tree_default': require('@/assets/environments/outdoor/tree_default.glb'),
  'outdoor/tree_fat': require('@/assets/environments/outdoor/tree_fat.glb'),
  'outdoor/tree_oak': require('@/assets/environments/outdoor/tree_oak.glb'),
  'outdoor/tree_pineRoundA': require('@/assets/environments/outdoor/tree_pineRoundA.glb'),
  'outdoor/tree_pineTallA': require('@/assets/environments/outdoor/tree_pineTallA.glb'),
  'outdoor/tree_small': require('@/assets/environments/outdoor/tree_small.glb'),
};
